services:
  baserow:
    image: baserow/baserow:1.33.2
    restart: always
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - baserow_data:/baserow/data

volumes:
  baserow_data:
    driver: local
    driver_opts:
      type: none
      device: ./baserow_data
      o: bind
